from __main__ import config
from email.policy import default
from owlready2 import default_world

# not using graphDB, only internal glboal_DB dict and sqlite3 for owlready2
# If use graphDB
# If authentication required, set username='grapdb login username', password='graphdb login password'
# default_world.set_backend(backend="sparql-endpoint",
#                           endpoint="http://localhost:7200/repositories/compass-test", debug=False)

# default_world.set_backend(filename='./db.sqlite')

PREFIX = 'cp'

compass_url = 'https://github.com/csse-uoft/compass-ontology/releases/download/latest/compass.owl'

namespaces = {
    'act':    'http://ontology.eil.utoronto.ca/tove/activity#',
    'dcat':    'http://www.w3.org/ns/dcat#',
    'ic':    'http://ontology.eil.utoronto.ca/tove/icontact#',
    'icontact':    'http://ontology.eil.utoronto.ca/tove/icontact#',
    'owl':  'http://www.w3.org/2002/07/owl#',

    'wgs':  'http://www.w3.org/2003/01/geo/wgs84_pos/',
    'sch':  'http://schema.org/',
    'sur':    'http://ontology.eil.utoronto.ca/tove/survey#',
    'dqv':    'http://www.w3.org/ns/dqv#',
    'qb':    'http://purl.org/linked-data/cube#',
    'dcterms':    'http://purl.org/dc/terms/',
    'loc_50871':    'http://ontology.eil.utoronto.ca/5087/1/SpatialLoc/',
    'act_50871':    'http://ontology.eil.utoronto.ca/5087/1/Activity#',
    'city_50872':    'http://ontology.eil.utoronto.ca/5087/2/City#',
    'cityservice_50872':    'http://ontology.eil.utoronto.ca/5087/2/CityService#',
    'landuse_50872':    'http://ontology.eil.utoronto.ca/5087/2/LandUse/',

    'time':    'http://www.w3.org/2006/time#',
    'oep':    'http://www.w3.org/2001/sw/BestPractices/OEP/SimplePartWhole/part.owl#',
    'xsd':    'http://www.w3.org/2001/XMLSchema#',
    'rdf':    'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    'rdfs':    'http://www.w3.org/2000/01/rdf-schema#',
    'foaf':    'http://xmlns.com/foaf/0.1/',
    'rel':    'http://purl.org/vocab/relationship/',
    'geo':    'http://www.opengis.net/ont/geosparql#',
    'i72':    'http://ontology.eil.utoronto.ca/ISO21972/iso21972#',
    'org':    'http://ontology.eil.utoronto.ca/tove/organization#',
    'cids':    'http://ontology.eil.utoronto.ca/cids/cids#',
    'cp':    'http://helpseeker.co/compass#',
}

TURTLE_PREAMBLE = '''
################################################################
# Turtle File Generated by: cra-pipeline
# Date : %s
# github: https://github.com/csse-uoft/cra-pipeline
################################################################
'''%(config.FILE_DATE)
for prefix, url in namespaces.items():
    TURTLE_PREAMBLE += f"@prefix {prefix}:  <{url}>.\n"

prefix, url ='compass', 'http://helpseeker.co/compass#'
TURTLE_PREAMBLE += f"@prefix {prefix}:  <{url}>.\n"

TURTLE_PREAMBLE += '''
<local> rdf:type owl:Ontology ;
    owl:imports <%s> .

'''%(compass_url)



print('Loading/Downloading ontologies, if the script stuck here, try re-run it.')
default_world.set_backend(filename='./db.sqlite')
compass = default_world.get_ontology(compass_url).load(reload=True)

print('Ontology Loaded.')
for prefix, url in namespaces.items():
    if prefix != '':
        exec(f"{prefix} = default_world.get_namespace('{url}')")


# some properties in OwlReady2 don't show the range type. This overwrites any that are found in the ontology.
# usage in uti;l.save_db_as_ttl() and util.row_to_turtle()
prop_ranges_preset = {
    cids.hasDescription:[str],
    org.hasName:[str],
    org.hasLegalName:[str],
    sch.description:[str],
    dcterms.description:[str],
    ic.hasCityS:[str],
    ic.hasPostalCode:[str],
    ic.hasStreet:[str],
    ic.hasStreetNumber:[str],
    cids.hasWebAddress:[str],
    ic.hasPhoneNumber:[int],
    org.hasIdentifier:[str],
}
